-- Recipe Management App schema
-- Run this once in the Supabase SQL editor for your project.
--
-- Data model: recipes, the shopping list, and everything else here belongs
-- to a *family* (a household group), not to an individual user — every
-- member of a family sees and edits the same shared collection, and
-- different families are fully isolated from each other. A user belongs to
-- at most one family at a time. New families are created self-serve from
-- the app; joining an existing one requires an invite link generated by an
-- existing member (see family_invites below) — there is no public "browse
-- families" or open sign-up-into-anything flow.
--
-- IMPORTANT — manual step in the Supabase dashboard: family invites work by
-- having the invited person create their own account (email + password)
-- when they open the invite link, so "Authentication -> Settings -> Allow
-- new users to sign up" must be ON for this project. The app itself never
-- exposes a public "create account" entry point outside of a valid invite
-- link, so this does not open the app to unrelated strangers signing up —
-- an account created without a valid invite/create-family call just has no
-- family and sees nothing.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- families / family_members: the sharing boundary for everything else in
-- this file. A user_id can only ever appear in one family_members row —
-- that's what makes "one family per user" an actual constraint rather than
-- just an app-level convention.
-- ---------------------------------------------------------------------------
create table if not exists public.families (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.family_members (
  user_id uuid primary key references auth.users (id) on delete cascade,
  family_id uuid not null references public.families (id) on delete cascade,
  display_name text not null,
  role text not null default 'member',
  joined_at timestamptz not null default now()
);

alter table public.family_members drop constraint if exists family_members_role_check;
alter table public.family_members add constraint family_members_role_check
  check (role in ('owner', 'member'));

-- One of the app's curated accent-preset ids (see ACCENT_PRESETS in
-- src/lib/settings-store.ts) — null until someone picks one, in which case
-- the UI falls back to the default accent color. Not a free-form hex value:
-- keeping it to the same closed palette used for the app's own theming
-- means a member's color always has a matching, tested foreground pair.
alter table public.family_members add column if not exists color text;

create index if not exists family_members_family_id_idx on public.family_members (family_id);

-- The signed-in user's family, or null if they're not in one yet. security
-- definer + stable so every RLS policy below can reuse it directly instead
-- of re-deriving "which family am I in" each time (and without needing its
-- own read access to family_members, which would be circular).
create or replace function public.current_family_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select family_id from public.family_members where user_id = auth.uid();
$$;

alter table public.families enable row level security;
alter table public.family_members enable row level security;

drop policy if exists "Members can read their own family" on public.families;
create policy "Members can read their own family"
  on public.families for select
  to authenticated
  using (id = public.current_family_id());

drop policy if exists "Owners can rename their family" on public.families;
create policy "Owners can rename their family"
  on public.families for update
  to authenticated
  using (id = public.current_family_id())
  with check (id = public.current_family_id());

drop policy if exists "Members can read their family's members" on public.family_members;
create policy "Members can read their family's members"
  on public.family_members for select
  to authenticated
  using (family_id = public.current_family_id());

drop policy if exists "Members can update their own display name" on public.family_members;
create policy "Members can update their own display name"
  on public.family_members for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and family_id = public.current_family_id());

drop policy if exists "Owners can remove other members" on public.family_members;
create policy "Owners can remove other members"
  on public.family_members for delete
  to authenticated
  using (
    family_id = public.current_family_id()
    and user_id <> auth.uid()
    and exists (
      select 1 from public.family_members m
      where m.user_id = auth.uid() and m.role = 'owner'
    )
  );

-- Lets any family member set the display color of *any* member (not just
-- their own) — the household is a trusted, fully co-equal group everywhere
-- else in this schema (recipes, shopping list, known items all work the
-- same way), and color-picking for the whole household from one screen is
-- exactly how the settings page is meant to be used. Deliberately a
-- separate RPC rather than broadening the "update their own display name"
-- policy above, so that policy's self-only restriction on renaming stays
-- intact — this only ever touches the color column.
create or replace function public.set_member_color(target_user_id uuid, new_color text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.family_members
    where user_id = target_user_id and family_id = public.current_family_id()
  ) then
    raise exception 'המשתמש אינו חבר במשפחה שלך';
  end if;

  update public.family_members set color = new_color where user_id = target_user_id;
end;
$$;

grant execute on function public.set_member_color(uuid, text) to authenticated;

-- No direct insert policy on families/family_members: membership only ever
-- changes through create_family()/redeem_family_invite() below (both
-- security definer), which enforce "exactly one family per user" and
-- "only via a valid, unused, unexpired invite" — rules a raw insert policy
-- can't express safely (an unrestricted family_members insert would let
-- anyone add themselves to any family_id they can guess).

create or replace function public.create_family(family_name text, member_display_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_family_id uuid;
begin
  if exists (select 1 from public.family_members where user_id = auth.uid()) then
    raise exception 'כבר יש לך משפחה';
  end if;
  if btrim(coalesce(family_name, '')) = '' or btrim(coalesce(member_display_name, '')) = '' then
    raise exception 'יש להזין שם משפחה ושם תצוגה';
  end if;

  insert into public.families (name, created_by) values (btrim(family_name), auth.uid())
  returning id into new_family_id;

  insert into public.family_members (user_id, family_id, display_name, role)
  values (auth.uid(), new_family_id, btrim(member_display_name), 'owner');

  return new_family_id;
end;
$$;

grant execute on function public.create_family(text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- family_invites: single-use, expiring links (not emails — see the note at
-- the top of this file) that let an existing member bring someone else into
-- their family.
-- ---------------------------------------------------------------------------
create table if not exists public.family_invites (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families (id) on delete cascade,
  token text not null unique,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '14 days'),
  used_by uuid references auth.users (id) on delete set null,
  used_at timestamptz
);

create index if not exists family_invites_token_idx on public.family_invites (token);
create index if not exists family_invites_family_id_idx on public.family_invites (family_id);

alter table public.family_invites enable row level security;

drop policy if exists "Members can read their family's invites" on public.family_invites;
create policy "Members can read their family's invites"
  on public.family_invites for select
  to authenticated
  using (family_id = public.current_family_id());

drop policy if exists "Members can create invites for their family" on public.family_invites;
create policy "Members can create invites for their family"
  on public.family_invites for insert
  to authenticated
  with check (family_id = public.current_family_id());

drop policy if exists "Members can delete their family's invites" on public.family_invites;
create policy "Members can delete their family's invites"
  on public.family_invites for delete
  to authenticated
  using (family_id = public.current_family_id());

-- Lets the (not-yet-signed-up, not-yet-authenticated) recipient of an
-- invite link see whose family they're about to join, and whether the link
-- is still valid, before they create an account — the only thing in this
-- file granted to the anon role, and it only ever reveals a family's
-- display name for one exact, unguessable token.
create or replace function public.get_invite_preview(invite_token text)
returns table(family_name text, is_valid boolean)
language sql
stable
security definer
set search_path = public
as $$
  select f.name, (fi.used_at is null and fi.expires_at > now())
  from public.family_invites fi
  join public.families f on f.id = fi.family_id
  where fi.token = invite_token;
$$;

grant execute on function public.get_invite_preview(text) to anon, authenticated;

create or replace function public.redeem_family_invite(invite_token text, member_display_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_family_id uuid;
begin
  if exists (select 1 from public.family_members where user_id = auth.uid()) then
    raise exception 'כבר יש לך משפחה';
  end if;
  if btrim(coalesce(member_display_name, '')) = '' then
    raise exception 'יש להזין שם תצוגה';
  end if;

  select family_id into target_family_id
  from public.family_invites
  where token = invite_token and used_at is null and expires_at > now();

  if target_family_id is null then
    raise exception 'קישור ההזמנה לא תקין או שפג תוקפו';
  end if;

  insert into public.family_members (user_id, family_id, display_name, role)
  values (auth.uid(), target_family_id, btrim(member_display_name), 'member');

  update public.family_invites
  set used_by = auth.uid(), used_at = now()
  where token = invite_token;

  return target_family_id;
end;
$$;

grant execute on function public.redeem_family_invite(text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Admin-only, cross-family introspection/management, gated to a single
-- hardcoded email (the app's owner) rather than a general roles system —
-- there's exactly one person who needs this, and a real roles table would
-- be overkill for a household app. Every function here re-checks the email
-- itself (not just a client-side check) since these bypass the normal
-- "your own family only" boundary that the rest of this file enforces.
-- ---------------------------------------------------------------------------
create or replace function public.admin_list_users()
returns table(
  user_id uuid,
  email text,
  display_name text,
  role text,
  family_id uuid,
  family_name text,
  joined_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.email() <> 'galsela2@gmail.com' then
    raise exception 'אין הרשאה';
  end if;

  return query
    select u.id, u.email, fm.display_name, fm.role, f.id, f.name, fm.joined_at
    from auth.users u
    left join public.family_members fm on fm.user_id = u.id
    left join public.families f on f.id = fm.family_id
    order by u.created_at asc;
end;
$$;

grant execute on function public.admin_list_users() to authenticated;

create or replace function public.admin_rename_member(target_user_id uuid, new_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.email() <> 'galsela2@gmail.com' then
    raise exception 'אין הרשאה';
  end if;
  if btrim(coalesce(new_name, '')) = '' then
    raise exception 'יש להזין שם';
  end if;

  update public.family_members set display_name = btrim(new_name) where user_id = target_user_id;
end;
$$;

grant execute on function public.admin_rename_member(uuid, text) to authenticated;

create or replace function public.admin_remove_member(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.email() <> 'galsela2@gmail.com' then
    raise exception 'אין הרשאה';
  end if;

  delete from public.family_members where user_id = target_user_id;
end;
$$;

grant execute on function public.admin_remove_member(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- recipes
-- ---------------------------------------------------------------------------
create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  image_url text,
  source_url text,
  prep_time_minutes integer,
  cook_time_minutes integer,
  servings integer,
  ingredients jsonb not null default '[]'::jsonb,
  instructions jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}'::text[],
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Structured dietary/allergen attributes, separate from freeform tags, for
-- the multi-select filter sidebar (e.g. Low-Carb, Gluten-Free, Dairy-Free).
alter table public.recipes
  add column if not exists dietary_tags text[] not null default '{}'::text[];

-- Shared household favorite flag (one flag per recipe, not per-user — same
-- sharing model as the rest of this app).
alter table public.recipes
  add column if not exists is_favorite boolean not null default false;

-- Who made this recipe, as an actual family member rather than a fixed pair
-- of hardcoded names — nullable, since "who made it" isn't always relevant.
alter table public.recipes
  add column if not exists made_by_user_id uuid references auth.users (id) on delete set null;

alter table public.recipes add column if not exists family_id uuid references public.families (id);

-- ---------------------------------------------------------------------------
-- shopping_list_items
-- ---------------------------------------------------------------------------
create table if not exists public.shopping_list_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  checked boolean not null default false,
  recipe_id uuid references public.recipes (id) on delete set null,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.shopping_list_items add column if not exists family_id uuid references public.families (id);

-- ---------------------------------------------------------------------------
-- known_items: a durable, ever-growing pool of ingredient / shopping-list
-- text you've entered before, so the app can suggest it instead of you
-- retyping it. Rows are never deleted by app usage (unlike shopping list
-- items, which get cleared), so suggestions persist across shopping trips.
-- Scoped per family — see the (family_id, name) primary key migrated in
-- further down, replacing the old globally-unique "name" primary key.
-- ---------------------------------------------------------------------------
create table if not exists public.known_items (
  name text not null,
  use_count integer not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.known_items
  add column if not exists pinned boolean not null default false;
alter table public.known_items add column if not exists family_id uuid references public.families (id);

-- ---------------------------------------------------------------------------
-- recipe_photos: user-taken "real result" photos, kept separate from the
-- recipe's cover image (recipes.image_url) and date-stamped so they can be
-- shown as a dated cooking history.
-- ---------------------------------------------------------------------------
create table if not exists public.recipe_photos (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes (id) on delete cascade,
  url text not null,
  taken_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.recipe_photos add column if not exists family_id uuid references public.families (id);

-- One-time migration from the earlier flat `recipes.photos text[]` column,
-- if it still exists on this database.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'recipes' and column_name = 'photos'
  ) then
    insert into public.recipe_photos (recipe_id, url, taken_at, created_by, family_id)
    select r.id, photo_url, r.created_at, r.created_by, r.family_id
    from public.recipes r, unnest(r.photos) as photo_url
    where r.photos is not null and array_length(r.photos, 1) > 0;

    alter table public.recipes drop column photos;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- One-time data migration: everything above used to be shared globally
-- between exactly two hardcoded accounts. The first time this script runs
-- on a database from before families existed, this creates one default
-- family for those two accounts (matched by the emails the app always
-- used) and backfills every existing row's family_id to it, so nothing
-- already in the database becomes invisible once the family-scoped
-- policies further down take effect. Safe to re-run: guarded to only touch
-- rows that don't have a family_id yet, and a no-op on a fresh database
-- with no legacy rows.
-- ---------------------------------------------------------------------------
do $$
declare
  default_family_id uuid;
  gal_id uuid;
  niva_id uuid;
begin
  if not exists (select 1 from public.recipes where family_id is null)
     and not exists (select 1 from public.shopping_list_items where family_id is null)
     and not exists (select 1 from public.known_items where family_id is null)
     and not exists (select 1 from public.recipe_photos where family_id is null)
  then
    return;
  end if;

  select id into gal_id from auth.users where email = 'galsela2@gmail.com';
  select id into niva_id from auth.users where email = 'nivatesler@gmail.com';

  select id into default_family_id from public.families where name = 'ניבה וגל' limit 1;
  if default_family_id is null then
    insert into public.families (name, created_by)
    values ('ניבה וגל', coalesce(gal_id, niva_id))
    returning id into default_family_id;
  end if;

  if gal_id is not null then
    insert into public.family_members (user_id, family_id, display_name, role)
    values (gal_id, default_family_id, 'גל', 'owner')
    on conflict (user_id) do nothing;
  end if;
  if niva_id is not null then
    insert into public.family_members (user_id, family_id, display_name, role)
    values (niva_id, default_family_id, 'ניבה', 'owner')
    on conflict (user_id) do nothing;
  end if;

  update public.recipes set family_id = default_family_id where family_id is null;
  update public.shopping_list_items set family_id = default_family_id where family_id is null;
  update public.known_items set family_id = default_family_id where family_id is null;
  update public.recipe_photos set family_id = default_family_id where family_id is null;
end $$;

-- family_id becomes required only once nothing is left without one — so a
-- fresh database, or one where the migration above couldn't find a
-- matching auth.users row, doesn't get stuck mid-migration.
do $$
begin
  if not exists (select 1 from public.recipes where family_id is null) then
    execute 'alter table public.recipes alter column family_id set not null';
  end if;
  if not exists (select 1 from public.shopping_list_items where family_id is null) then
    execute 'alter table public.shopping_list_items alter column family_id set not null';
  end if;
  if not exists (select 1 from public.known_items where family_id is null) then
    execute 'alter table public.known_items alter column family_id set not null';
  end if;
  if not exists (select 1 from public.recipe_photos where family_id is null) then
    execute 'alter table public.recipe_photos alter column family_id set not null';
  end if;
end $$;

-- One-time migration from the old fixed-enum `recipes.made_by text` column
-- ('ניבה' | 'גל' | 'משותף') to made_by_user_id, matched by display_name
-- against the family_members rows just created above. Runs after the
-- family backfill so those rows actually exist to match against. 'משותף'
-- (shared/both) has no single-user equivalent and is intentionally dropped
-- rather than guessed at.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'recipes' and column_name = 'made_by'
  ) then
    update public.recipes r set made_by_user_id = fm.user_id
    from public.family_members fm
    where r.made_by = fm.display_name and r.made_by_user_id is null;

    alter table public.recipes drop constraint if exists recipes_made_by_check;
    alter table public.recipes drop column made_by;
  end if;
end $$;

-- Switches known_items from a single global "name" primary key to a
-- per-family (family_id, name) one. Whatever primary key currently exists
-- (none, on a fresh table; the old name-only one; or already this composite
-- one, if this script has run before) is normalized to the composite one.
do $$
declare
  existing_pk_name text;
begin
  select conname into existing_pk_name
  from pg_constraint
  where conrelid = 'public.known_items'::regclass and contype = 'p';

  if existing_pk_name is not null and existing_pk_name <> 'known_items_family_id_name_pkey' then
    execute format('alter table public.known_items drop constraint %I', existing_pk_name);
    existing_pk_name := null;
  end if;

  if existing_pk_name is null then
    execute 'alter table public.known_items add constraint known_items_family_id_name_pkey primary key (family_id, name)';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- recipes: indexes, constraints, trigger, and RLS (after family_id/
-- made_by_user_id above are fully migrated and non-null).
-- ---------------------------------------------------------------------------
create index if not exists recipes_created_at_idx on public.recipes (created_at desc);
create index if not exists recipes_family_id_idx on public.recipes (family_id);
create index if not exists recipes_tags_idx on public.recipes using gin (tags);
create index if not exists recipes_dietary_tags_idx on public.recipes using gin (dietary_tags);
create index if not exists recipes_made_by_user_id_idx on public.recipes (made_by_user_id);

-- Non-negative guards on user-entered numeric fields (the client already
-- enforces min={0}, but that's not a substitute for a DB-level constraint).
alter table public.recipes drop constraint if exists recipes_prep_time_minutes_check;
alter table public.recipes add constraint recipes_prep_time_minutes_check
  check (prep_time_minutes is null or prep_time_minutes >= 0);

alter table public.recipes drop constraint if exists recipes_cook_time_minutes_check;
alter table public.recipes add constraint recipes_cook_time_minutes_check
  check (cook_time_minutes is null or cook_time_minutes >= 0);

alter table public.recipes drop constraint if exists recipes_servings_check;
alter table public.recipes add constraint recipes_servings_check
  check (servings is null or servings >= 0);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists recipes_set_updated_at on public.recipes;
create trigger recipes_set_updated_at
  before update on public.recipes
  for each row
  execute function public.set_updated_at();

alter table public.recipes enable row level security;

drop policy if exists "Authenticated users can read recipes" on public.recipes;
drop policy if exists "Family members can read their family's recipes" on public.recipes;
create policy "Family members can read their family's recipes"
  on public.recipes for select
  to authenticated
  using (family_id = public.current_family_id());

drop policy if exists "Authenticated users can insert recipes" on public.recipes;
drop policy if exists "Family members can insert recipes for their family" on public.recipes;
create policy "Family members can insert recipes for their family"
  on public.recipes for insert
  to authenticated
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can update recipes" on public.recipes;
drop policy if exists "Family members can update their family's recipes" on public.recipes;
create policy "Family members can update their family's recipes"
  on public.recipes for update
  to authenticated
  using (family_id = public.current_family_id())
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can delete recipes" on public.recipes;
drop policy if exists "Family members can delete their family's recipes" on public.recipes;
create policy "Family members can delete their family's recipes"
  on public.recipes for delete
  to authenticated
  using (family_id = public.current_family_id());

-- ---------------------------------------------------------------------------
-- recipe_shares: expiring tokens that let one specific recipe be read (and
-- optionally copied) by someone outside the owning family, via the share
-- button on the recipe page. The same link can be opened more than once.
-- ---------------------------------------------------------------------------
create table if not exists public.recipe_shares (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes (id) on delete cascade,
  token text not null unique,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create index if not exists recipe_shares_token_idx on public.recipe_shares (token);
create index if not exists recipe_shares_recipe_id_idx on public.recipe_shares (recipe_id);

alter table public.recipe_shares enable row level security;

drop policy if exists "Members can manage shares for their own family's recipes" on public.recipe_shares;
create policy "Members can manage shares for their own family's recipes"
  on public.recipe_shares for all
  to authenticated
  using (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_id and r.family_id = public.current_family_id()
    )
  )
  with check (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_id and r.family_id = public.current_family_id()
    )
  );

-- Reads a shared recipe by its share token regardless of the caller's own
-- family — the point of sharing — but still only for a signed-in app user
-- (matches "share to someone by link, but only if they're a registered
-- user" from how this feature was scoped), and only for a real, unexpired
-- token, never a general cross-family recipes read.
create or replace function public.get_shared_recipe(share_token text)
returns public.recipes
language sql
stable
security definer
set search_path = public
as $$
  select r.*
  from public.recipes r
  join public.recipe_shares s on s.recipe_id = r.id
  where s.token = share_token and s.expires_at > now();
$$;

grant execute on function public.get_shared_recipe(text) to authenticated;

-- Copies a shared recipe into the caller's own family as a brand new,
-- independent recipe (not a live reference to the original) — the
-- "הוספה לאוסף שלי" button on the shared-recipe page.
create or replace function public.import_shared_recipe(share_token text)
returns public.recipes
language plpgsql
security definer
set search_path = public
as $$
declare
  source_recipe public.recipes;
  my_family_id uuid;
  new_recipe public.recipes;
begin
  my_family_id := public.current_family_id();
  if my_family_id is null then
    raise exception 'עליך להיות חבר במשפחה כדי לייבא מתכון';
  end if;

  select r.* into source_recipe
  from public.recipes r
  join public.recipe_shares s on s.recipe_id = r.id
  where s.token = share_token and s.expires_at > now();

  if source_recipe.id is null then
    raise exception 'קישור השיתוף לא תקין או שפג תוקפו';
  end if;

  insert into public.recipes (
    title, description, image_url, source_url, prep_time_minutes, cook_time_minutes,
    servings, ingredients, instructions, tags, dietary_tags, family_id, created_by
  ) values (
    source_recipe.title, source_recipe.description, source_recipe.image_url, source_recipe.source_url,
    source_recipe.prep_time_minutes, source_recipe.cook_time_minutes, source_recipe.servings,
    source_recipe.ingredients, source_recipe.instructions, source_recipe.tags, source_recipe.dietary_tags,
    my_family_id, auth.uid()
  )
  returning * into new_recipe;

  return new_recipe;
end;
$$;

grant execute on function public.import_shared_recipe(text) to authenticated;

-- ---------------------------------------------------------------------------
-- shopping_list_items: indexes and RLS (after family_id above is fully
-- migrated and non-null).
-- ---------------------------------------------------------------------------
create index if not exists shopping_list_items_created_at_idx
  on public.shopping_list_items (created_at);
create index if not exists shopping_list_items_checked_idx
  on public.shopping_list_items (checked);
create index if not exists shopping_list_items_family_id_idx
  on public.shopping_list_items (family_id);

alter table public.shopping_list_items enable row level security;

drop policy if exists "Authenticated users can read shopping list" on public.shopping_list_items;
drop policy if exists "Family members can read their family's shopping list" on public.shopping_list_items;
create policy "Family members can read their family's shopping list"
  on public.shopping_list_items for select
  to authenticated
  using (family_id = public.current_family_id());

drop policy if exists "Authenticated users can insert shopping list items" on public.shopping_list_items;
drop policy if exists "Family members can insert shopping list items" on public.shopping_list_items;
create policy "Family members can insert shopping list items"
  on public.shopping_list_items for insert
  to authenticated
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can update shopping list items" on public.shopping_list_items;
drop policy if exists "Family members can update their family's shopping list items" on public.shopping_list_items;
create policy "Family members can update their family's shopping list items"
  on public.shopping_list_items for update
  to authenticated
  using (family_id = public.current_family_id())
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can delete shopping list items" on public.shopping_list_items;
drop policy if exists "Family members can delete their family's shopping list items" on public.shopping_list_items;
create policy "Family members can delete their family's shopping list items"
  on public.shopping_list_items for delete
  to authenticated
  using (family_id = public.current_family_id());

-- ---------------------------------------------------------------------------
-- known_items: index and RLS (after the family_id/composite-key migration
-- above).
-- ---------------------------------------------------------------------------
create index if not exists known_items_family_pinned_use_count_idx
  on public.known_items (family_id, pinned desc, use_count desc);

alter table public.known_items enable row level security;

drop policy if exists "Authenticated users can read known items" on public.known_items;
drop policy if exists "Family members can read their family's known items" on public.known_items;
create policy "Family members can read their family's known items"
  on public.known_items for select
  to authenticated
  using (family_id = public.current_family_id());

-- Incrementing use_count happens through record_known_item()/
-- record_known_items() (security definer below). These direct policies
-- cover the management drawer: manually adding, renaming, pinning, and
-- deleting suggestions.
drop policy if exists "Authenticated users can insert known items" on public.known_items;
drop policy if exists "Family members can insert their family's known items" on public.known_items;
create policy "Family members can insert their family's known items"
  on public.known_items for insert
  to authenticated
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can update known items" on public.known_items;
drop policy if exists "Family members can update their family's known items" on public.known_items;
create policy "Family members can update their family's known items"
  on public.known_items for update
  to authenticated
  using (family_id = public.current_family_id())
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can delete known items" on public.known_items;
drop policy if exists "Family members can delete their family's known items" on public.known_items;
create policy "Family members can delete their family's known items"
  on public.known_items for delete
  to authenticated
  using (family_id = public.current_family_id());

create or replace function public.record_known_item(item_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_family_id uuid;
begin
  if item_name is null or btrim(item_name) = '' then
    return;
  end if;

  caller_family_id := public.current_family_id();
  if caller_family_id is null then
    return;
  end if;

  insert into public.known_items (family_id, name, use_count, updated_at)
  values (caller_family_id, btrim(item_name), 1, now())
  on conflict (family_id, name)
  do update set
    use_count = public.known_items.use_count + 1,
    updated_at = now();
end;
$$;

grant execute on function public.record_known_item(text) to authenticated;

-- Batched variant of record_known_item, for callers recording many ingredient
-- names at once (a recipe save, a bulk shopping-list add) — one round trip
-- instead of one RPC call per item.
create or replace function public.record_known_items(item_names text[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item_name text;
  caller_family_id uuid;
begin
  caller_family_id := public.current_family_id();
  if caller_family_id is null then
    return;
  end if;

  foreach item_name in array item_names loop
    if item_name is not null and btrim(item_name) <> '' then
      insert into public.known_items (family_id, name, use_count, updated_at)
      values (caller_family_id, btrim(item_name), 1, now())
      on conflict (family_id, name)
      do update set
        use_count = public.known_items.use_count + 1,
        updated_at = now();
    end if;
  end loop;
end;
$$;

grant execute on function public.record_known_items(text[]) to authenticated;

-- ---------------------------------------------------------------------------
-- recipe_photos: index and RLS (after family_id above is fully migrated
-- and non-null).
-- ---------------------------------------------------------------------------
create index if not exists recipe_photos_recipe_id_idx on public.recipe_photos (recipe_id);
create index if not exists recipe_photos_family_id_idx on public.recipe_photos (family_id);

alter table public.recipe_photos enable row level security;

drop policy if exists "Authenticated users can read recipe photos" on public.recipe_photos;
drop policy if exists "Family members can read their family's recipe photos" on public.recipe_photos;
create policy "Family members can read their family's recipe photos"
  on public.recipe_photos for select
  to authenticated
  using (family_id = public.current_family_id());

drop policy if exists "Authenticated users can insert recipe photos" on public.recipe_photos;
drop policy if exists "Family members can insert their family's recipe photos" on public.recipe_photos;
create policy "Family members can insert their family's recipe photos"
  on public.recipe_photos for insert
  to authenticated
  with check (family_id = public.current_family_id());

drop policy if exists "Authenticated users can delete recipe photos" on public.recipe_photos;
drop policy if exists "Family members can delete their family's recipe photos" on public.recipe_photos;
create policy "Family members can delete their family's recipe photos"
  on public.recipe_photos for delete
  to authenticated
  using (family_id = public.current_family_id());

-- pantry_items and cook_logs were removed as features (the app no longer
-- reads or writes them); left in place, untouched, only so any data a
-- household already had isn't silently dropped. Not part of the family
-- model — see the app's git history if either is ever revived.

-- meal_plan_entries (weekly meal planner) was removed as an unwanted
-- feature. Drops it if a previous schema run created it on this database.
drop table if exists public.meal_plan_entries cascade;

-- ---------------------------------------------------------------------------
-- Storage: a public bucket for in-progress cooking photos. Public read
-- keeps the app simple (no signed-URL refreshing, and every URL is an
-- unguessable UUID path — not discoverable without already having the
-- link); writes are restricted to authenticated users.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('recipe-photos', 'recipe-photos', true)
on conflict (id) do nothing;

drop policy if exists "Authenticated users can upload recipe photos" on storage.objects;
create policy "Authenticated users can upload recipe photos"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'recipe-photos');

drop policy if exists "Authenticated users can delete recipe photos" on storage.objects;
create policy "Authenticated users can delete recipe photos"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'recipe-photos');

drop policy if exists "Anyone can view recipe photos" on storage.objects;
create policy "Anyone can view recipe photos"
  on storage.objects for select
  to public
  using (bucket_id = 'recipe-photos');

-- ---------------------------------------------------------------------------
-- Realtime: broadcast row changes for live sync within a family.
-- Guarded so re-running this script doesn't error on tables already added.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'recipes',
    'shopping_list_items',
    'known_items',
    'recipe_photos',
    'families',
    'family_members'
  ]
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
